#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Author: <Zurdi>
#
# This python scripts closes all processes that may be
# not killed properly, like the browsermob-proxy and
# it removes all log files generated by internal libraries


import sys
import os
import psutil

BASE_DIR = os.path.dirname(os.path.realpath(__file__))
sys.path.append(os.path.join(BASE_DIR, 'lib'))

from lib_log_nbz import Logging
logger = Logging()

if os.name == 'posix':
    ppid = os.getppid()
    logs = ['bmp.log', 'geckodriver.log', 'server.log', 'ghostdriver.log']
    for log in logs:
        if os.path.isfile(os.path.join(os.getcwd(), log)):
                os.remove(os.path.join(os.getcwd(), log))
    logger.log('NOTE', 'Connections closed')
    os.killpg(ppid, 9)

elif os.name == 'nt':
    #TODO all
    pass
